# Question bank for the "Buzzing with Kvizzing" quiz, seeded by
# recs/migrations/0012_seed_quiz_questions.py. Kept as its own module (rather
# than inlined in the migration) so it's easy to read and edit directly.
#
# Every question should be an "educated guess" for someone who hasn't seen
# the movie/show, built on iconic imagery, quotes, or premises, never
# obscure trivia. `review_note` flags anything worth double-checking before
# this goes live; it only shows up on the staff-only /quiz/test/ page.

QUIZ_QUESTIONS = [
    # --- Silence of the Lambs ---
    dict(
        movie_title="Silence of the Lambs",
        style="quote",
        prompt='"It puts the lotion on its skin, or it gets the hose again." Which serial-killer thriller is this chilling line from?',
        option_a="Silence of the Lambs",
        option_b="Se7en",
        option_c="American Psycho",
        correct_option="a",
    ),
    dict(
        movie_title="Silence of the Lambs",
        style="character",
        prompt="Which imprisoned cannibal-psychiatrist helps an FBI trainee profile a killer, in exchange for personal details about her life?",
        option_a="Hannibal Lecter",
        option_b="Norman Bates",
        option_c="Patrick Bateman",
        correct_option="a",
    ),
    # --- Godfather ---
    dict(
        movie_title="Godfather",
        style="emoji",
        prompt="🐴🔫🍊\nGuess the movie.",
        option_a="The Godfather",
        option_b="Goodfellas",
        option_c="Scarface",
        correct_option="a",
    ),
    dict(
        movie_title="Godfather",
        style="quote",
        prompt='"I\'m gonna make him an offer he can\'t refuse." Which mafia classic is this line from?',
        option_a="The Godfather",
        option_b="Casino",
        option_c="Once Upon a Time in America",
        correct_option="a",
    ),
    dict(
        movie_title="Godfather",
        style="plot",
        prompt="In this classic, a movie producer wakes up to find his prized horse's severed head in his bed, a mob warning he can't ignore.",
        option_a="The Godfather",
        option_b="Casino",
        option_c="Scarface",
        correct_option="a",
    ),
    # --- E.T. ---
    dict(
        movie_title="E.T.",
        style="emoji",
        prompt="👽🚲🌕\nGuess the movie.",
        option_a="E.T. the Extra-Terrestrial",
        option_b="Close Encounters of the Third Kind",
        option_c="Arrival",
        correct_option="a",
    ),
    dict(
        movie_title="E.T.",
        style="quote",
        prompt='"E.T. phone home." Which Spielberg classic features this line?',
        option_a="E.T. the Extra-Terrestrial",
        option_b="Jurassic Park",
        option_c="Close Encounters of the Third Kind",
        correct_option="a",
    ),
    # --- Terminator 2 ---
    dict(
        movie_title="Terminator 2",
        style="emoji",
        prompt="🤖👍🔥\nGuess the movie.",
        option_a="Terminator 2: Judgment Day",
        option_b="RoboCop",
        option_c="I, Robot",
        correct_option="a",
    ),
    dict(
        movie_title="Terminator 2",
        style="plot",
        prompt="A shape-shifting, liquid-metal assassin is sent back in time to kill a kid who'll grow up to lead the human resistance.",
        option_a="Terminator 2: Judgment Day",
        option_b="The Matrix",
        option_c="I, Robot",
        correct_option="a",
    ),
    dict(
        movie_title="Terminator 2",
        style="character",
        prompt="Which actor plays a killer cyborg who gets reprogrammed to be the good guy in this sequel?",
        option_a="Arnold Schwarzenegger",
        option_b="Sylvester Stallone",
        option_c="Dolph Lundgren",
        correct_option="a",
    ),
    # --- Gadar: Ek Prem Katha ---
    dict(
        movie_title="Gadar: Ek Prem Katha",
        style="plot",
        prompt="In this Bollywood blockbuster set around Partition, the hero famously rips a hand-pump out of the ground to use as a weapon.",
        option_a="Gadar: Ek Prem Katha",
        option_b="Sholay",
        option_c="Border",
        correct_option="a",
    ),
    dict(
        movie_title="Gadar: Ek Prem Katha",
        style="character",
        prompt="Sunny Deol plays a truck driver named Tara Singh who marries a Muslim woman and crosses the border to save her family, in which film?",
        option_a="Gadar: Ek Prem Katha",
        option_b="Border",
        option_c="Veer-Zaara",
        correct_option="a",
    ),
    # --- Braveheart ---
    dict(
        movie_title="Braveheart",
        style="quote",
        prompt='"They may take our lives, but they\'ll never take our FREEDOM!" Which historical epic builds to this cry?',
        option_a="Braveheart",
        option_b="Gladiator",
        option_c="300",
        correct_option="a",
    ),
    dict(
        movie_title="Braveheart",
        style="character",
        prompt="Mel Gibson plays a Scottish rebel with his face painted blue, leading a fight for independence from England.",
        option_a="Braveheart",
        option_b="Gladiator",
        option_c="Rob Roy",
        correct_option="a",
    ),
    # --- American Beauty ---
    dict(
        movie_title="American Beauty",
        style="plot",
        prompt="A suburban dad's midlife crisis includes an inappropriate fantasy about his teenage daughter's friend, imagined surrounded by rose petals.",
        option_a="American Beauty",
        option_b="The Ice Storm",
        option_c="Little Children",
        correct_option="a",
    ),
    dict(
        movie_title="American Beauty",
        style="plot",
        prompt="This Best Picture winner opens with a narrator calling a floating plastic bag 'the most beautiful thing' he's ever filmed.",
        option_a="American Beauty",
        option_b="Magnolia",
        option_c="Fight Club",
        correct_option="a",
    ),
    # --- The Hurt Locker ---
    dict(
        movie_title="The Hurt Locker",
        style="plot",
        prompt="This 2010 Best Picture winner follows a U.S. Army bomb-disposal unit in Iraq, and made its director the first woman ever to win Best Director.",
        option_a="The Hurt Locker",
        option_b="Zero Dark Thirty",
        option_c="American Sniper",
        correct_option="a",
    ),
    dict(
        movie_title="The Hurt Locker",
        style="character",
        prompt="A reckless sergeant on a bomb squad seems almost addicted to the adrenaline of defusing explosives one wire at a time, in which war drama?",
        option_a="The Hurt Locker",
        option_b="Zero Dark Thirty",
        option_c="Black Hawk Down",
        correct_option="a",
    ),
    # --- Matrix ---
    dict(
        movie_title="Matrix",
        style="emoji",
        prompt="🕶️💊🐇\nGuess the movie.",
        option_a="The Matrix",
        option_b="Inception",
        option_c="Equilibrium",
        correct_option="a",
    ),
    dict(
        movie_title="Matrix",
        style="quote",
        prompt='"There is no spoon." Which sci-fi classic is this line from?',
        option_a="The Matrix",
        option_b="Inception",
        option_c="Total Recall",
        correct_option="a",
    ),
    dict(
        movie_title="Matrix",
        style="plot",
        prompt="A hacker is offered a red pill or a blue pill to learn the unsettling truth about his simulated reality.",
        option_a="The Matrix",
        option_b="Dark City",
        option_c="Inception",
        correct_option="a",
    ),
    # --- Big Bang Theory ---
    dict(
        movie_title="Big Bang Theory",
        style="quote",
        prompt='"Bazinga!" is the catchphrase of a socially awkward physicist on which long-running sitcom?',
        option_a="The Big Bang Theory",
        option_b="Community",
        option_c="The IT Crowd",
        correct_option="a",
    ),
    dict(
        movie_title="Big Bang Theory",
        style="character",
        prompt="This sitcom follows nerdy Caltech scientists, one of whom insists on a strict 'Roommate Agreement' with his best friend.",
        option_a="The Big Bang Theory",
        option_b="Silicon Valley",
        option_c="Young Sheldon",
        correct_option="a",
    ),
    # --- Borat ---
    dict(
        movie_title="Borat",
        style="emoji",
        prompt="👙🎤🇰🇿\nGuess the movie.",
        option_a="Borat",
        option_b="Ali G Indahouse",
        option_c="Bruno",
        correct_option="a",
    ),
    dict(
        movie_title="Borat",
        style="character",
        prompt="Sacha Baron Cohen plays a fictional Kazakh TV journalist travelling across America, famous for a bright green mankini, in which mockumentary?",
        option_a="Borat",
        option_b="Bruno",
        option_c="The Dictator",
        correct_option="a",
    ),
    # --- Days of our Lives ---
    dict(
        movie_title="Days of our Lives",
        style="quote",
        prompt='"Like sands through the hourglass, so are the Days of our Lives." This opening line belongs to which long-running soap opera?',
        option_a="Days of our Lives",
        option_b="General Hospital",
        option_c="The Young and the Restless",
        correct_option="a",
    ),
    dict(
        movie_title="Days of our Lives",
        style="plot",
        prompt="Set in the fictional town of Salem, this American soap opera has been airing new weekday episodes since the 1960s.",
        option_a="Days of our Lives",
        option_b="As the World Turns",
        option_c="General Hospital",
        correct_option="a",
    ),
    # --- Sooryavansham ---
    dict(
        movie_title="Sooryavansham",
        style="plot",
        prompt="In this Hindi remake of a Telugu hit, one lead actor plays both an uneducated son and, in flashback, his own strict father.",
        option_a="Sooryavansham",
        option_b="Baghban",
        option_c="Black",
        correct_option="a",
        review_note="Confirm the dual-role/remake premise before this goes live.",
    ),
    dict(
        movie_title="Sooryavansham",
        style="character",
        prompt="Amitabh Bachchan plays a father and son in the same family in this film, one famous in India for airing on TV almost every single day.",
        option_a="Sooryavansham",
        option_b="Mohabbatein",
        option_c="Baghban",
        correct_option="a",
    ),
    # --- Game of Thrones ---
    dict(
        movie_title="Game of Thrones",
        style="quote",
        prompt='"Winter is coming." This is the words of House Stark in which fantasy series?',
        option_a="Game of Thrones",
        option_b="The Witcher",
        option_c="The Wheel of Time",
        correct_option="a",
    ),
    dict(
        movie_title="Game of Thrones",
        style="plot",
        prompt="Noble houses scheme for the Iron Throne while dragons and an army of the dead threaten the realm, in which HBO series?",
        option_a="Game of Thrones",
        option_b="House of the Dragon",
        option_c="The Witcher",
        correct_option="a",
    ),
    dict(
        movie_title="Game of Thrones",
        style="plot",
        prompt="A wedding in this series turns into such a massacre that fans just call it 'The Red Wedding.'",
        option_a="Game of Thrones",
        option_b="Vikings",
        option_c="The Last Kingdom",
        correct_option="a",
    ),
    # --- Snow White ---
    dict(
        movie_title="Snow White",
        style="emoji",
        prompt="🍎👸🪞\nGuess the movie.",
        option_a="Snow White and the Seven Dwarfs",
        option_b="Sleeping Beauty",
        option_c="Cinderella",
        correct_option="a",
    ),
    dict(
        movie_title="Snow White",
        style="quote",
        prompt='"Mirror, mirror, on the wall, who\'s the fairest one of all?" This line is from which Disney classic?',
        option_a="Snow White and the Seven Dwarfs",
        option_b="Sleeping Beauty",
        option_c="Shrek",
        correct_option="a",
    ),
    # --- Breaking Bad ---
    dict(
        movie_title="Breaking Bad",
        style="quote",
        prompt='"I am the one who knocks." Which chemistry-teacher-turned-drug-lord says this?',
        option_a="Walter White, in Breaking Bad",
        option_b="Marty Byrde, in Ozark",
        option_c="Chuck Rhoades, in Billions",
        correct_option="a",
    ),
    dict(
        movie_title="Breaking Bad",
        style="plot",
        prompt="A high-school chemistry teacher diagnosed with cancer starts cooking meth to secure his family's future, in which show?",
        option_a="Breaking Bad",
        option_b="Ozark",
        option_c="Narcos",
        correct_option="a",
    ),
    dict(
        movie_title="Breaking Bad",
        style="character",
        prompt="This show's mild-mannered chemistry teacher takes on the secret alias 'Heisenberg' once he goes full drug kingpin.",
        option_a="Breaking Bad",
        option_b="Better Call Saul",
        option_c="Ozark",
        correct_option="a",
    ),
    # --- Sherlock Holmes ---
    dict(
        movie_title="Sherlock Holmes",
        style="character",
        prompt="This pipe-smoking detective lives at 221B Baker Street with his loyal friend and chronicler, Dr. Watson.",
        option_a="Sherlock Holmes",
        option_b="Hercule Poirot",
        option_c="Inspector Gadget",
        correct_option="a",
    ),
    dict(
        movie_title="Sherlock Holmes",
        style="plot",
        prompt="Created by Arthur Conan Doyle, this deerstalker-hat-wearing detective solves crimes through pure deduction and observation.",
        option_a="Sherlock Holmes",
        option_b="Sam Spade",
        option_c="Columbo",
        correct_option="a",
    ),
    # --- Harry Potter ---
    dict(
        movie_title="Harry Potter",
        style="emoji",
        prompt="⚡🧙‍♂️🦉\nGuess the movie/franchise.",
        option_a="Harry Potter",
        option_b="The Chronicles of Narnia",
        option_c="Percy Jackson",
        correct_option="a",
    ),
    dict(
        movie_title="Harry Potter",
        style="quote",
        prompt='"Expecto Patronum!" is a spell used to ward off soul-sucking Dementors in which franchise?',
        option_a="Harry Potter",
        option_b="The Chronicles of Narnia",
        option_c="Percy Jackson",
        correct_option="a",
    ),
    dict(
        movie_title="Harry Potter",
        style="character",
        prompt="A lightning-bolt scar on his forehead marks this boy as 'The Boy Who Lived,' destined to face a dark wizard.",
        option_a="Harry Potter",
        option_b="Percy Jackson",
        option_c="Eragon",
        correct_option="a",
    ),
    # --- The Simpsons ---
    dict(
        movie_title="The Simpsons",
        style="quote",
        prompt='"D\'oh!" is the go-to exclamation of which yellow, bald sitcom dad?',
        option_a="Homer Simpson",
        option_b="Peter Griffin",
        option_c="Fred Flintstone",
        correct_option="a",
    ),
    dict(
        movie_title="The Simpsons",
        style="plot",
        prompt="This is the longest-running American scripted primetime series ever, following a yellow-skinned family in the town of Springfield.",
        option_a="The Simpsons",
        option_b="Family Guy",
        option_c="South Park",
        correct_option="a",
    ),
    # --- Frasier ---
    dict(
        movie_title="Frasier",
        style="character",
        prompt="This Seattle radio psychiatrist, spun off from a sitcom set in a Boston bar, bickers lovingly with his brother Niles and ex-cop father.",
        option_a="Frasier",
        option_b="Cheers",
        option_c="Wings",
        correct_option="a",
    ),
    dict(
        movie_title="Frasier",
        style="plot",
        prompt="The title character of this sitcom shares his apartment with his father and his father's scene-stealing dog, Eddie.",
        option_a="Frasier",
        option_b="Cheers",
        option_c="Becker",
        correct_option="a",
    ),
    # --- Django Unchained ---
    dict(
        movie_title="Django Unchained",
        style="emoji",
        prompt="🤠⛓️🔫\nGuess the movie.",
        option_a="Django Unchained",
        option_b="The Hateful Eight",
        option_c="True Grit",
        correct_option="a",
    ),
    dict(
        movie_title="Django Unchained",
        style="plot",
        prompt="A freed slave teams up with a German bounty hunter to rescue his wife from a ruthless plantation owner, in which Tarantino film?",
        option_a="Django Unchained",
        option_b="Inglourious Basterds",
        option_c="The Hateful Eight",
        correct_option="a",
    ),
    dict(
        movie_title="Django Unchained",
        style="character",
        prompt="Which actor plays the charming, sadistic plantation owner Calvin Candie?",
        option_a="Leonardo DiCaprio",
        option_b="Christoph Waltz",
        option_c="Samuel L. Jackson",
        correct_option="a",
    ),
    # --- Finding Nemo ---
    dict(
        movie_title="Finding Nemo",
        style="emoji",
        prompt="🐠🌊🔍\nGuess the movie.",
        option_a="Finding Nemo",
        option_b="Shark Tale",
        option_c="The Little Mermaid",
        correct_option="a",
    ),
    dict(
        movie_title="Finding Nemo",
        style="quote",
        prompt='"Just keep swimming." Which forgetful blue fish says this in a Pixar classic?',
        option_a="Dory, in Finding Nemo",
        option_b="Flounder, in The Little Mermaid",
        option_c="Bubbles, in Shark Tale",
        correct_option="a",
    ),
    # --- Prison Break ---
    dict(
        movie_title="Prison Break",
        style="plot",
        prompt="The hero gets himself intentionally imprisoned with the prison's blueprint tattooed across his entire body, to break his brother out.",
        option_a="Prison Break",
        option_b="Oz",
        option_c="Escape at Dannemora",
        correct_option="a",
    ),
    dict(
        movie_title="Prison Break",
        style="character",
        prompt="Michael Scofield's elaborate tattoo-based escape plan is meant to save his brother, who's on death row, in which show?",
        option_a="Prison Break",
        option_b="Breaking Bad",
        option_c="The Wire",
        correct_option="a",
    ),
    # --- The Princess Bride ---
    dict(
        movie_title="The Princess Bride",
        style="quote",
        prompt='"Hello, my name is Inigo Montoya. You killed my father. Prepare to die." This revenge-fueled swordsman is from which film?',
        option_a="The Princess Bride",
        option_b="The Three Musketeers",
        option_c="Zorro",
        correct_option="a",
    ),
    dict(
        movie_title="The Princess Bride",
        style="quote",
        prompt='"As you wish" is secretly code for "I love you" between the two leads of which fairy-tale adventure?',
        option_a="The Princess Bride",
        option_b="Shrek",
        option_c="Ella Enchanted",
        correct_option="a",
    ),
    dict(
        movie_title="The Princess Bride",
        style="plot",
        prompt="This film features Rodents Of Unusual Size, a Pit of Despair, and a fencing master seeking revenge for his father.",
        option_a="The Princess Bride",
        option_b="Willow",
        option_c="Stardust",
        correct_option="a",
    ),
    # --- Panchayat ---
    dict(
        movie_title="Panchayat",
        style="plot",
        prompt="An engineering graduate reluctantly takes a government job as secretary of a small village council in UP, in this Amazon Prime Video series.",
        option_a="Panchayat",
        option_b="Gullak",
        option_c="Kota Factory",
        correct_option="a",
    ),
    dict(
        movie_title="Panchayat",
        style="character",
        prompt="Jitendra Kumar plays Abhishek Tripathi, a reluctant village panchayat secretary, in which slice-of-life Indian series?",
        option_a="Panchayat",
        option_b="Kota Factory",
        option_c="Gullak",
        correct_option="a",
    ),
    dict(
        movie_title="Panchayat",
        style="emoji",
        prompt="🏡📜🗳️\nGuess the show.",
        option_a="Panchayat",
        option_b="The Family Man",
        option_c="Gullak",
        correct_option="a",
    ),
    # --- Sacred Games ---
    dict(
        movie_title="Sacred Games",
        style="character",
        prompt="Nawazuddin Siddiqui plays gangster Ganesh Gaitonde opposite Saif Ali Khan's world-weary cop, in which Netflix India series?",
        option_a="Sacred Games",
        option_b="Mirzapur",
        option_c="The Family Man",
        correct_option="a",
    ),
    dict(
        movie_title="Sacred Games",
        style="plot",
        prompt="Based on a Vikram Chandra novel, this Netflix India thriller jumps between a Mumbai cop's present-day investigation and a gangster's rise to power.",
        option_a="Sacred Games",
        option_b="Mirzapur",
        option_c="Paatal Lok",
        correct_option="a",
    ),
    # --- The Mentalist ---
    dict(
        movie_title="The Mentalist",
        style="character",
        prompt="A former fake psychic turned police consultant uses cold-reading and observation tricks to solve crimes, always hunting a serial killer called Red John.",
        option_a="The Mentalist",
        option_b="Lie to Me",
        option_c="Psych",
        correct_option="a",
    ),
    dict(
        movie_title="The Mentalist",
        style="plot",
        prompt="The sharply dressed lead of this crime procedural never carries a badge or a gun, solving cases through mentalism tricks instead.",
        option_a="The Mentalist",
        option_b="Psych",
        option_c="Monk",
        correct_option="a",
    ),
    # --- Die Hard ---
    dict(
        movie_title="Die Hard",
        style="emoji",
        prompt="🏢🎄🔫\nGuess the movie.",
        option_a="Die Hard",
        option_b="Lethal Weapon",
        option_c="Speed",
        correct_option="a",
    ),
    dict(
        movie_title="Die Hard",
        style="quote",
        prompt='"Yippee-ki-yay" is the catchphrase of a barefoot cop trapped in a skyscraper on Christmas Eve, in which film?',
        option_a="Die Hard",
        option_b="Lethal Weapon",
        option_c="Speed",
        correct_option="a",
    ),
    dict(
        movie_title="Die Hard",
        style="plot",
        prompt="This film sparks an annual internet debate over whether it counts as a Christmas movie, since it's set at an office holiday party under siege.",
        option_a="Die Hard",
        option_b="Lethal Weapon",
        option_c="The Long Kiss Goodnight",
        correct_option="a",
    ),
    # --- Get Out ---
    dict(
        movie_title="Get Out",
        style="emoji",
        prompt="🫖🌀😨\nGuess the movie.",
        option_a="Get Out",
        option_b="Us",
        option_c="Nope",
        correct_option="a",
    ),
    dict(
        movie_title="Get Out",
        style="plot",
        prompt="A Black man visiting his white girlfriend's family for the weekend discovers a horrifying secret involving hypnosis and a teacup, in which Jordan Peele film?",
        option_a="Get Out",
        option_b="Us",
        option_c="Nope",
        correct_option="a",
    ),
    dict(
        movie_title="Get Out",
        style="plot",
        prompt="Getting hypnotized in this film sends victims into a terrifying state called 'the sunken place.'",
        option_a="Get Out",
        option_b="Us",
        option_c="Nope",
        correct_option="a",
    ),
    # --- Face/Off ---
    dict(
        movie_title="Face/Off",
        style="emoji",
        prompt="😷🔄🕊️\nGuess the movie.",
        option_a="Face/Off",
        option_b="The Mask",
        option_c="Con Air",
        correct_option="a",
    ),
    dict(
        movie_title="Face/Off",
        style="plot",
        prompt="A cop and a terrorist literally swap faces via surgery to infiltrate each other's lives, in this over-the-top John Woo action film.",
        option_a="Face/Off",
        option_b="Con Air",
        option_c="The Rock",
        correct_option="a",
    ),
    # --- Back to the Future ---
    dict(
        movie_title="Back to the Future",
        style="emoji",
        prompt="🚗⚡🕰️\nGuess the movie.",
        option_a="Back to the Future",
        option_b="The Terminator",
        option_c="Looper",
        correct_option="a",
    ),
    dict(
        movie_title="Back to the Future",
        style="quote",
        prompt='"Great Scott! We need 1.21 gigawatts!" This line is from which time-travel classic?',
        option_a="Back to the Future",
        option_b="The Time Machine",
        option_c="Looper",
        correct_option="a",
    ),
    dict(
        movie_title="Back to the Future",
        style="plot",
        prompt="A teenager accidentally travels back to 1955 in a modified DeLorean and has to make sure his own parents fall in love.",
        option_a="Back to the Future",
        option_b="Interstellar",
        option_c="Looper",
        correct_option="a",
    ),
    # --- Memento ---
    dict(
        movie_title="Memento",
        style="plot",
        prompt="Told mostly in reverse, this thriller follows a man with short-term memory loss who tattoos clues onto his own body to hunt his wife's killer.",
        option_a="Memento",
        option_b="Shutter Island",
        option_c="The Machinist",
        correct_option="a",
    ),
    dict(
        movie_title="Memento",
        style="character",
        prompt="The protagonist of this Christopher Nolan film can't form new memories after a head injury, so he relies on Polaroids and notes to piece together his own investigation.",
        option_a="Memento",
        option_b="Inception",
        option_c="Source Code",
        correct_option="a",
    ),
    # --- Pulp Fiction ---
    dict(
        movie_title="Pulp Fiction",
        style="quote",
        prompt='"Royale with cheese" is what they call a Quarter Pounder in Paris, according to two hitmen in which film?',
        option_a="Pulp Fiction",
        option_b="Reservoir Dogs",
        option_c="True Romance",
        correct_option="a",
    ),
    dict(
        movie_title="Pulp Fiction",
        style="plot",
        prompt="This Tarantino film features a mysterious glowing briefcase whose contents are never revealed to the audience.",
        option_a="Pulp Fiction",
        option_b="Kill Bill",
        option_c="Reservoir Dogs",
        correct_option="a",
    ),
    dict(
        movie_title="Pulp Fiction",
        style="plot",
        prompt="Told out of chronological order, this film weaves together a boxer, two hitmen, and a gangster's wife across interlocking stories.",
        option_a="Pulp Fiction",
        option_b="Reservoir Dogs",
        option_c="Jackie Brown",
        correct_option="a",
    ),
    # --- Rocky ---
    dict(
        movie_title="Rocky",
        style="quote",
        prompt='"Yo, Adrian!" is shouted by which underdog boxer after a career-defining fight?',
        option_a="Rocky Balboa, in Rocky",
        option_b="Jake LaMotta, in Raging Bull",
        option_c="Billy Hoyle, in White Men Can't Jump",
        correct_option="a",
    ),
    dict(
        movie_title="Rocky",
        style="plot",
        prompt="This underdog boxing film is famous for its training montage of running up the steps of the Philadelphia Museum of Art.",
        option_a="Rocky",
        option_b="Raging Bull",
        option_c="Creed",
        correct_option="a",
    ),
    # --- Sholay ---
    dict(
        movie_title="Sholay",
        style="quote",
        prompt='"Kitne aadmi the?" ("How many men were there?") is barked by the villain of which iconic Bollywood dacoit film?',
        option_a="Sholay",
        option_b="Zanjeer",
        option_c="Don",
        correct_option="a",
    ),
    dict(
        movie_title="Sholay",
        style="character",
        prompt="Gabbar Singh, one of Bollywood's most iconic villains, terrorizes a village until two small-time crooks are hired to stop him, in which classic?",
        option_a="Sholay",
        option_b="Zanjeer",
        option_c="Don",
        correct_option="a",
    ),
    dict(
        movie_title="Sholay",
        style="emoji",
        prompt="🐎🔫🎬\n(a classic Bollywood dacoit western) Guess the movie.",
        option_a="Sholay",
        option_b="Gadar: Ek Prem Katha",
        option_c="Lagaan",
        correct_option="a",
    ),
    # --- Chernobyl ---
    dict(
        movie_title="Chernobyl",
        style="emoji",
        prompt="☢️🏭💥\nGuess the show.",
        option_a="Chernobyl",
        option_b="Chernobyl Diaries",
        option_c="Oppenheimer",
        correct_option="a",
    ),
    dict(
        movie_title="Chernobyl",
        style="quote",
        prompt='"What is the cost of lies?" is the haunting tagline of which HBO miniseries about a 1986 nuclear disaster?',
        option_a="Chernobyl",
        option_b="Chernobyl Diaries",
        option_c="The China Syndrome",
        correct_option="a",
    ),
    dict(
        movie_title="Chernobyl",
        style="plot",
        prompt="This miniseries follows Soviet scientists and officials scrambling to contain the fallout of a nuclear reactor meltdown in Ukraine.",
        option_a="Chernobyl",
        option_b="The Hot Zone",
        option_c="Oppenheimer",
        correct_option="a",
    ),
    # --- Tummbad ---
    dict(
        movie_title="Tummbad",
        style="plot",
        prompt="In this Indian horror film, a family guards a secret room where a monstrous, ancient god must be fed to yield gold.",
        option_a="Tummbad",
        option_b="Stree",
        option_c="Bulbbul",
        correct_option="a",
        review_note="Double-check the Hastar mythology details before this goes live.",
    ),
    dict(
        movie_title="Tummbad",
        style="emoji",
        prompt="🌾👹💰\n(an Indian folk-horror tale about a forbidden god of grain and gold) Guess the movie.",
        option_a="Tummbad",
        option_b="Stree",
        option_c="Bulbbul",
        correct_option="a",
    ),
    # --- The Mummy ---
    dict(
        movie_title="The Mummy",
        style="emoji",
        prompt="🐫⚱️👻\nGuess the movie.",
        option_a="The Mummy",
        option_b="Indiana Jones",
        option_c="Night at the Museum",
        correct_option="a",
    ),
    dict(
        movie_title="The Mummy",
        style="plot",
        prompt="Adventurers accidentally resurrect an ancient, cursed Egyptian priest while exploring the buried city of Hamunaptra.",
        option_a="The Mummy",
        option_b="Raiders of the Lost Ark",
        option_c="Night at the Museum",
        correct_option="a",
    ),
    # --- Mission Impossible ---
    dict(
        movie_title="Mission Impossible",
        style="quote",
        prompt='"This message will self-destruct in five seconds." This classic mission-briefing line belongs to which spy franchise?',
        option_a="Mission: Impossible",
        option_b="James Bond",
        option_c="The Bourne Identity",
        correct_option="a",
    ),
    dict(
        movie_title="Mission Impossible",
        style="plot",
        prompt="An agent dangles from wires to avoid touching the floor while stealing a file from a high-security vault, in the first film of which franchise?",
        option_a="Mission: Impossible",
        option_b="James Bond",
        option_c="Ocean's Eleven",
        correct_option="a",
    ),
    dict(
        movie_title="Mission Impossible",
        style="character",
        prompt="Which actor has played secret agent Ethan Hunt across this entire long-running spy franchise?",
        option_a="Tom Cruise",
        option_b="Matt Damon",
        option_c="Pierce Brosnan",
        correct_option="a",
    ),
    # --- The Shining ---
    dict(
        movie_title="The Shining",
        style="quote",
        prompt='"Here\'s Johnny!" is shouted through a chopped-open door by a man slowly losing his mind at an isolated hotel.',
        option_a="The Shining",
        option_b="Misery",
        option_c="1408",
        correct_option="a",
    ),
    dict(
        movie_title="The Shining",
        style="plot",
        prompt="A family becomes the winter caretakers of a remote, possibly haunted hotel, and the father slowly descends into murderous madness.",
        option_a="The Shining",
        option_b="1408",
        option_c="Doctor Sleep",
        correct_option="a",
    ),
    dict(
        movie_title="The Shining",
        style="plot",
        prompt="Twin girls appear at the end of a hallway, and a boy rides his tricycle past a river of blood, in this Stanley Kubrick horror classic.",
        option_a="The Shining",
        option_b="The Others",
        option_c="Doctor Sleep",
        correct_option="a",
    ),
    # --- Raging Bull ---
    dict(
        movie_title="Raging Bull",
        style="character",
        prompt="Robert De Niro famously gained a large amount of weight to play an aging, self-destructive boxer in this black-and-white biopic.",
        option_a="Raging Bull",
        option_b="Rocky",
        option_c="The Wrestler",
        correct_option="a",
    ),
    dict(
        movie_title="Raging Bull",
        style="plot",
        prompt="This Martin Scorsese biopic tells the real story of hot-tempered middleweight boxing champion Jake LaMotta.",
        option_a="Raging Bull",
        option_b="Rocky",
        option_c="Cinderella Man",
        correct_option="a",
    ),
    # --- X-Files ---
    dict(
        movie_title="X-Files",
        style="quote",
        prompt='"The Truth Is Out There" is the tagline of which paranormal-investigation TV series?',
        option_a="The X-Files",
        option_b="Fringe",
        option_c="Stranger Things",
        correct_option="a",
    ),
    dict(
        movie_title="X-Files",
        style="character",
        prompt="FBI agents Mulder and Scully investigate unexplained, often alien-related cases in which long-running show?",
        option_a="The X-Files",
        option_b="Fringe",
        option_c="Supernatural",
        correct_option="a",
    ),
    # --- Andhadhun ---
    dict(
        movie_title="Andhadhun",
        style="plot",
        prompt="A pianist pretends to be blind, then accidentally witnesses a murder he's not supposed to have 'seen,' in this Hindi thriller.",
        option_a="Andhadhun",
        option_b="Drishyam",
        option_c="Badla",
        correct_option="a",
    ),
    dict(
        movie_title="Andhadhun",
        style="character",
        prompt="Tabu plays a dangerously cunning woman entangled in a cover-up with a pianist who may or may not really be blind, in which film?",
        option_a="Andhadhun",
        option_b="Drishyam",
        option_c="Kahaani",
        correct_option="a",
    ),
    # --- Yuva ---
    dict(
        movie_title="Yuva",
        style="plot",
        prompt="This Mani Ratnam film weaves together three separate stories of young men in Kolkata, whose lives collide around the Howrah Bridge.",
        option_a="Yuva",
        option_b="Rang De Basanti",
        option_c="Dil Chahta Hai",
        correct_option="a",
        review_note="Confirm the Howrah Bridge plot detail before this goes live.",
    ),
    dict(
        movie_title="Yuva",
        style="character",
        prompt="Ajay Devgn, Abhishek Bachchan, and Vivek Oberoi play three very different young men whose paths intertwine in one fateful day, in which film?",
        option_a="Yuva",
        option_b="Dil Chahta Hai",
        option_c="Company",
        correct_option="a",
    ),
    # --- The Family Man ---
    dict(
        movie_title="The Family Man",
        style="plot",
        prompt="A middle-class secret agent balances stopping terror plots with attending his kids' school events and hiding his real job from his family, in this series.",
        option_a="The Family Man",
        option_b="Special Ops",
        option_c="Mirzapur",
        correct_option="a",
    ),
    dict(
        movie_title="The Family Man",
        style="character",
        prompt="Manoj Bajpayee plays Srikant Tiwari, a secret intelligence officer posing as an ordinary IT employee, in which show?",
        option_a="The Family Man",
        option_b="Special Ops",
        option_c="Rocket Boys",
        correct_option="a",
    ),
    dict(
        movie_title="The Family Man",
        style="emoji",
        prompt="🕵️‍♂️👨‍👩‍👧‍👦💣\nGuess the show.",
        option_a="The Family Man",
        option_b="Special Ops",
        option_c="Mirzapur",
        correct_option="a",
    ),
    # --- Sound of Music ---
    dict(
        movie_title="Sound of Music",
        style="emoji",
        prompt="🎵⛰️👗\nGuess the movie.",
        option_a="The Sound of Music",
        option_b="Mary Poppins",
        option_c="Annie",
        correct_option="a",
    ),
    dict(
        movie_title="Sound of Music",
        style="quote",
        prompt='"Do-Re-Mi" is taught by a singing governess to a family of seven children in which classic musical?',
        option_a="The Sound of Music",
        option_b="Mary Poppins",
        option_c="Annie",
        correct_option="a",
    ),
    # --- Eternal Sunshine of the Spotless Mind ---
    dict(
        movie_title="Eternal Sunshine of the Spotless Mind",
        style="plot",
        prompt="After a painful breakup, a heartbroken man hires a company to erase every memory of his ex-girlfriend from his mind.",
        option_a="Eternal Sunshine of the Spotless Mind",
        option_b="The Vow",
        option_c="50 First Dates",
        correct_option="a",
    ),
    dict(
        movie_title="Eternal Sunshine of the Spotless Mind",
        style="character",
        prompt="Jim Carrey and Kate Winslet play exes who both secretly get their memories of each other erased, in this Michel Gondry film.",
        option_a="Eternal Sunshine of the Spotless Mind",
        option_b="The Notebook",
        option_c="50 First Dates",
        correct_option="a",
    ),
]
