# Generated by Django 6.1.1 on 2026-09-16 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('rec_type', models.CharField(choices=[('movie', 'Movie'), ('book', 'Book'), ('podcast', 'Podcast'), ('game', 'Game'), ('subreddit', 'Subreddit'), ('ig_handle', 'Instagram Handle'), ('music', 'Music'), ('other', 'Other')], max_length=20)),
                ('other_type_label', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(help_text='The thing being recommended', max_length=200)),
                ('description', models.TextField(help_text='Who will love it and why')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThankYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_yous', to='recs.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
