# Generated by Django 6.1.1 on 2026-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rec_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('anime', 'Anime'), ('book', 'Book'), ('podcast', 'Podcast'), ('game', 'Game'), ('subreddit', 'Subreddit'), ('ig_handle', 'Instagram Handle'), ('music', 'Music'), ('other', 'Other')], max_length=20),
        ),
    ]
