# Generated by Django 6.1.1 on 2026-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0002_alter_recommendation_rec_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'karma',
                'ordering': ['-points'],
            },
        ),
        migrations.AddField(
            model_name='thankyou',
            name='sender_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
