# Generated by Django 6.1.1 on 2026-09-16 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0003_karma_thankyou_sender_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_name', models.CharField(max_length=120)),
                ('inviter_email', models.EmailField(max_length=254)),
                ('friend_name', models.CharField(max_length=120)),
                ('friend_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
