# Generated by Django 6.1.1 on 2026-09-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0004_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(help_text='Karma points required to reach this tier', unique=True)),
                ('tier_name', models.CharField(max_length=60)),
                ('unlock_text', models.CharField(help_text='Shown under the tier name, emoji included', max_length=200)),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
    ]
