# Generated by Django 6.1.1 on 2026-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0006_seed_karma_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='karmatier',
            name='email_teaser',
            field=models.CharField(blank=True, help_text="Closing line for the weekly 'you're close to a tier' email", max_length=200),
        ),
    ]
