# Generated by Django 6.1.1 on 2026-09-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0008_seed_karma_tier_email_teasers'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='access_url',
            field=models.URLField(blank=True, help_text='Where to watch/read/buy this — the play button links here'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Poster/cover image shown in the list and home carousel'),
        ),
    ]
