# Generated by Django 6.1.1 on 2026-09-27 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0010_seed_recommendation_media_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(help_text='Which title from the quiz list this is about', max_length=120)),
                ('style', models.CharField(choices=[('emoji', 'Emoji clue'), ('quote', 'Dialogue quote'), ('character', 'Character/actor'), ('plot', 'Plot descriptor')], default='plot', max_length=20)),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(max_length=150)),
                ('option_b', models.CharField(max_length=150)),
                ('option_c', models.CharField(max_length=150)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('review_note', models.CharField(blank=True, help_text='QA flag shown only on the staff-only /quiz/test/ page', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['movie_title', 'id'],
            },
        ),
    ]
